### ISSUE TITLE
Week 1 Review Ticket

### ISSUE THREAD

**Issue by LindaLiu1202** [samayasankuratri/flask_portfolio#13]
**Scrum Team Project Review**

- [x] [Design ](https://github.com/PranaviInukurti/flask_portfolio/issues/17)- [Wiki Theme:](https://github.com/PranaviInukurti/flask_portfolio/wiki/Design-Lead---Wiki-Theme) [Brain Write:](https://docs.google.com/document/d/1Fgip2Fr26XOBEdhVSpi1QiwjZowhopY57o4UpwbYZzo/edit?usp=sharing) & [Wire Frame:](https://www.figma.com/file/9CvmDXms787Ban053NP0Gf/StudyOwl?node-id=4%3A2)
- [x] [Technicals ](https://github.com/PranaviInukurti/flask_portfolio/issues/16)- [10  to 12 key ideas](https://docs.google.com/document/d/1Fgip2Fr26XOBEdhVSpi1QiwjZowhopY57o4UpwbYZzo/edit?usp=sharing) 
- [x] [Github ](https://github.com/PranaviInukurti/flask_portfolio/issues/15)- On Wiki containing [Management Plan](https://github.com/PranaviInukurti/flask_portfolio/wiki/Management-Plan)
- [x] [Deployment ](https://github.com/PranaviInukurti/flask_portfolio/issues/14)- [Wiki Plan, Hardware and Frequency](https://github.com/PranaviInukurti/flask_portfolio/wiki/Deployment-Guide)
- [x] [Scrum Board](https://github.com/PranaviInukurti/flask_portfolio/projects/1) - [Assignments and Backlog](https://github.com/PranaviInukurti/flask_portfolio/projects/1)

**Individual Create Task Understanding and Score, Notes, on TPT**

- [x] [TPT 0.0](https://docs.google.com/document/d/1OkAMgzNODur6Gtonz_EuvoDeVXUnaMvdthtZnsBjXwU/edit?usp=sharing
), Create Task ideas, notes, and research
- [x] [1.3 Program Design and Development](https://github.com/PranaviInukurti/flask_portfolio/issues/12)
- [x] [1.4 Identifying and Correcting Errors
](https://github.com/PranaviInukurti/flask_portfolio/issues/12)
- [link to video notes](https://docs.google.com/document/d/1d9Na70Eh9PwYkwA7uTLhpQwcjV4-c7aF8ZzhXGbdXwY/edit?usp=sharing)

**Grading Plan**

- [x] Readme Time-box and Review Ticket required
- [x] Preliminary grading on W or Th with Cross Over team, including Review Ticket comments and score per individual
- [x] Live grading from preliminary grading Review Ticket by Teacher on Th and F, including adjustments from cross over grading
- [x] Final, old point review.   Adjustment from Seed or Week 0

**Comment by Pitsco** [comment]
4.9/5
Team Name: Study Owls
Team Reviewing: The ninjas
Why 4.9/5? Their GitHub is well constructed and has issues that are well designed. A small improvement is to add a bit more details when writing the wikis. 
All tasks were complete when grading.

**Comment by jm1021** [comment]
Owls - Pranavi  4.8/5
* Brainwrite tools study planner avatar nice wires 1/1
* Nice research of  other ideas. .9/1
* Procedure or process for success  .9/1
* Deployment a little behind because of equip. 1/1
* Scrum Board looks good, good discussion behind task 1/1

**Comment by jm1021** [comment]
Thanks for attention to detail, score raised to 8/8 for all.
